# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/rc_metastudio/forms/about_legal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutLegalDialog(object):
    def setupUi(self, AboutLegalDialog):
        AboutLegalDialog.setObjectName("AboutLegalDialog")
        AboutLegalDialog.resize(0, 0)
        self.verticalLayout = QtWidgets.QVBoxLayout(AboutLegalDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.content_scroll_area = QtWidgets.QTextBrowser(AboutLegalDialog)
        self.content_scroll_area.setOpenExternalLinks(True)
        self.content_scroll_area.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.content_scroll_area.sizePolicy().hasHeightForWidth())
        self.content_scroll_area.setSizePolicy(sizePolicy)
        self.content_scroll_area.setObjectName("content_scroll_area")
        self.verticalLayout.addWidget(self.content_scroll_area)
        self.buttonBox = QtWidgets.QDialogButtonBox(AboutLegalDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AboutLegalDialog)
        self.buttonBox.rejected.connect(AboutLegalDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AboutLegalDialog)

    def retranslateUi(self, AboutLegalDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutLegalDialog.setWindowTitle(_translate("AboutLegalDialog", "About/Legal"))
import icons_rc
