# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/rc_metastudio/forms/conf_level_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_change_conf_level_dialog(object):
    def setupUi(self, change_conf_level_dialog):
        change_conf_level_dialog.setObjectName("change_conf_level_dialog")
        change_conf_level_dialog.resize(0, 0)
        self.dialog_layout = QtWidgets.QVBoxLayout(change_conf_level_dialog)
        self.dialog_layout.setObjectName("dialog_layout")
        self.content_layout = QtWidgets.QFormLayout()
        self.content_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.content_layout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.content_layout.setObjectName("content_layout")
        self.conf_level_label = QtWidgets.QLabel(change_conf_level_dialog)
        self.conf_level_label.setWordWrap(True)
        self.conf_level_label.setObjectName("conf_level_label")
        self.content_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.conf_level_label)
        self.conf_level_spinbox = QtWidgets.QDoubleSpinBox(change_conf_level_dialog)
        self.conf_level_spinbox.setDecimals(1)
        self.conf_level_spinbox.setMinimum(50.0)
        self.conf_level_spinbox.setMaximum(99.99999999999999)
        self.conf_level_spinbox.setSingleStep(0.1)
        self.conf_level_spinbox.setObjectName("conf_level_spinbox")
        self.content_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.conf_level_spinbox)
        self.dialog_layout.addLayout(self.content_layout)
        self.button_box = QtWidgets.QDialogButtonBox(change_conf_level_dialog)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.dialog_layout.addWidget(self.button_box)

        self.retranslateUi(change_conf_level_dialog)
        QtCore.QMetaObject.connectSlotsByName(change_conf_level_dialog)

    def retranslateUi(self, change_conf_level_dialog):
        _translate = QtCore.QCoreApplication.translate
        change_conf_level_dialog.setWindowTitle(_translate("change_conf_level_dialog", "Change Confidence Level"))
        self.conf_level_label.setText(_translate("change_conf_level_dialog", "Global Confidence Level:"))
        self.conf_level_spinbox.setSuffix(_translate("change_conf_level_dialog", "%"))
