# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/rc_metastudio/forms/cov_subgroup_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cov_subgroup_dialog(object):
    def setupUi(self, cov_subgroup_dialog):
        cov_subgroup_dialog.setObjectName("cov_subgroup_dialog")
        cov_subgroup_dialog.resize(0, 0)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/misc/meta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        cov_subgroup_dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(cov_subgroup_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(cov_subgroup_dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cov_subgroup_cbo_box = AdaptiveComboBox(cov_subgroup_dialog)
        self.cov_subgroup_cbo_box.setObjectName("cov_subgroup_cbo_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cov_subgroup_cbo_box)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(cov_subgroup_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label.setBuddy(self.cov_subgroup_cbo_box)

        self.retranslateUi(cov_subgroup_dialog)
        QtCore.QMetaObject.connectSlotsByName(cov_subgroup_dialog)

    def retranslateUi(self, cov_subgroup_dialog):
        _translate = QtCore.QCoreApplication.translate
        cov_subgroup_dialog.setWindowTitle(_translate("cov_subgroup_dialog", "Select Covariate"))
        self.label.setText(_translate("cov_subgroup_dialog", "Covariate for subgroups:"))
from adaptive_controls import AdaptiveComboBox
