# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/rc_metastudio/forms/change_group_name_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_group_name_dialog(object):
    def setupUi(self, group_name_dialog):
        group_name_dialog.setObjectName("group_name_dialog")
        group_name_dialog.resize(0, 0)
        self.verticalLayout = QtWidgets.QVBoxLayout(group_name_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.formLayout.setObjectName("formLayout")
        self.field_lbl = QtWidgets.QLabel(group_name_dialog)
        self.field_lbl.setObjectName("field_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.field_lbl)
        self.group_name_le = QtWidgets.QLineEdit(group_name_dialog)
        self.group_name_le.setAlignment(QtCore.Qt.AlignCenter)
        self.group_name_le.setObjectName("group_name_le")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.group_name_le)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(group_name_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.field_lbl.setBuddy(self.group_name_le)

        self.retranslateUi(group_name_dialog)
        self.buttonBox.accepted.connect(group_name_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(group_name_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(group_name_dialog)

    def retranslateUi(self, group_name_dialog):
        _translate = QtCore.QCoreApplication.translate
        group_name_dialog.setWindowTitle(_translate("group_name_dialog", "Edit Group Name"))
        self.field_lbl.setText(_translate("group_name_dialog", "Group name:"))
import icons_rc
