# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_follow_up_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_follow_up_dialog(object):
    def setupUi(self, new_follow_up_dialog):
        new_follow_up_dialog.setObjectName("new_follow_up_dialog")
        new_follow_up_dialog.resize(0, 0)
        self.verticalLayout = QtWidgets.QVBoxLayout(new_follow_up_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(new_follow_up_dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.follow_up_name_le = QtWidgets.QLineEdit(new_follow_up_dialog)
        self.follow_up_name_le.setAlignment(QtCore.Qt.AlignCenter)
        self.follow_up_name_le.setObjectName("follow_up_name_le")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.follow_up_name_le)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(new_follow_up_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_2.setBuddy(self.follow_up_name_le)

        self.retranslateUi(new_follow_up_dialog)
        self.buttonBox.accepted.connect(new_follow_up_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(new_follow_up_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(new_follow_up_dialog)

    def retranslateUi(self, new_follow_up_dialog):
        _translate = QtCore.QCoreApplication.translate
        new_follow_up_dialog.setWindowTitle(_translate("new_follow_up_dialog", "Add Follow-Up"))
        self.label_2.setText(_translate("new_follow_up_dialog", "Follow-up label"))
import icons_rc
