# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'network_view_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_network_view_dialog(object):
    def setupUi(self, network_view_dialog):
        network_view_dialog.setObjectName("network_view_dialog")
        network_view_dialog.resize(0, 0)
        self.verticalLayout = QtWidgets.QVBoxLayout(network_view_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.network_viewer = QtWidgets.QGraphicsView(network_view_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.network_viewer.sizePolicy().hasHeightForWidth())
        self.network_viewer.setSizePolicy(sizePolicy)
        self.network_viewer.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.network_viewer.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.network_viewer.setAlignment(QtCore.Qt.AlignCenter)
        self.network_viewer.setObjectName("network_viewer")
        self.verticalLayout.addWidget(self.network_viewer)
        self.frame = QtWidgets.QFrame(network_view_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.outcome_cbo_box = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outcome_cbo_box.sizePolicy().hasHeightForWidth())
        self.outcome_cbo_box.setSizePolicy(sizePolicy)
        self.outcome_cbo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.outcome_cbo_box.setObjectName("outcome_cbo_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.outcome_cbo_box)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.follow_up_cbo_box = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.follow_up_cbo_box.sizePolicy().hasHeightForWidth())
        self.follow_up_cbo_box.setSizePolicy(sizePolicy)
        self.follow_up_cbo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.follow_up_cbo_box.setObjectName("follow_up_cbo_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.follow_up_cbo_box)
        self.verticalLayout.addWidget(self.frame)
        self.label_3.setBuddy(self.outcome_cbo_box)
        self.label_4.setBuddy(self.follow_up_cbo_box)

        self.retranslateUi(network_view_dialog)
        QtCore.QMetaObject.connectSlotsByName(network_view_dialog)
        network_view_dialog.setTabOrder(self.network_viewer, self.outcome_cbo_box)
        network_view_dialog.setTabOrder(self.outcome_cbo_box, self.follow_up_cbo_box)

    def retranslateUi(self, network_view_dialog):
        _translate = QtCore.QCoreApplication.translate
        network_view_dialog.setWindowTitle(_translate("network_view_dialog", "Network"))
        self.label_3.setText(_translate("network_view_dialog", "Outcome:"))
        self.label_4.setText(_translate("network_view_dialog", "Follow-up:"))
