# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_covariate_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_covariate_dialog(object):
    def setupUi(self, new_covariate_dialog):
        new_covariate_dialog.setObjectName("new_covariate_dialog")
        new_covariate_dialog.resize(0, 0)
        self.verticalLayout = QtWidgets.QVBoxLayout(new_covariate_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(new_covariate_dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.covariate_name_le = QtWidgets.QLineEdit(new_covariate_dialog)
        self.covariate_name_le.setAlignment(QtCore.Qt.AlignCenter)
        self.covariate_name_le.setObjectName("covariate_name_le")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.covariate_name_le)
        self.label = QtWidgets.QLabel(new_covariate_dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.datatype_cbo_box = QtWidgets.QComboBox(new_covariate_dialog)
        self.datatype_cbo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.datatype_cbo_box.setMinimumContentsLength(12)
        self.datatype_cbo_box.setObjectName("datatype_cbo_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.datatype_cbo_box)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(new_covariate_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_2.setBuddy(self.covariate_name_le)
        self.label.setBuddy(self.datatype_cbo_box)

        self.retranslateUi(new_covariate_dialog)
        self.buttonBox.accepted.connect(new_covariate_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(new_covariate_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(new_covariate_dialog)
        new_covariate_dialog.setTabOrder(self.covariate_name_le, self.datatype_cbo_box)

    def retranslateUi(self, new_covariate_dialog):
        _translate = QtCore.QCoreApplication.translate
        new_covariate_dialog.setWindowTitle(_translate("new_covariate_dialog", "Add Covariate"))
        self.label_2.setText(_translate("new_covariate_dialog", "Covariate name:"))
        self.label.setText(_translate("new_covariate_dialog", "Type of covariate:"))
import icons_rc
