# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ali-Salman\Documents\Biostatistics\openmeta-analyst-community\src\rc_metastudio\forms\outcome_name_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(285, 46)
        WizardPage.setMinimumSize(QtCore.QSize(285, 45))
        WizardPage.setMaximumSize(QtCore.QSize(300, 50))
        WizardPage.setSubTitle("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(WizardPage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(WizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.outcome_name_LineEdit = QtWidgets.QLineEdit(WizardPage)
        self.outcome_name_LineEdit.setEnabled(True)
        self.outcome_name_LineEdit.setText("")
        self.outcome_name_LineEdit.setObjectName("outcome_name_LineEdit")
        self.horizontalLayout.addWidget(self.outcome_name_LineEdit)
        self.label.setBuddy(self.outcome_name_LineEdit)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage"))
        WizardPage.setTitle(_translate("WizardPage", "What is the name of your outcome?"))
        self.label.setText(_translate("WizardPage", "Outcome Name:"))
