# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ali-Salman\Documents\Biostatistics\openmeta-analyst-community\src\forms\cov_subgroup_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cov_subgroup_dialog(object):
    def setupUi(self, cov_subgroup_dialog):
        cov_subgroup_dialog.setObjectName("cov_subgroup_dialog")
        cov_subgroup_dialog.resize(301, 132)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        cov_subgroup_dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/misc/meta.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        cov_subgroup_dialog.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(cov_subgroup_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 100, 281, 32))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(cov_subgroup_dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cov_subgroup_cbo_box = QtWidgets.QComboBox(cov_subgroup_dialog)
        self.cov_subgroup_cbo_box.setGeometry(QtCore.QRect(130, 40, 152, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.cov_subgroup_cbo_box.setFont(font)
        self.cov_subgroup_cbo_box.setObjectName("cov_subgroup_cbo_box")

        self.retranslateUi(cov_subgroup_dialog)
        QtCore.QMetaObject.connectSlotsByName(cov_subgroup_dialog)

    def retranslateUi(self, cov_subgroup_dialog):
        _translate = QtCore.QCoreApplication.translate
        cov_subgroup_dialog.setWindowTitle(_translate("cov_subgroup_dialog", "Select Covariate"))
        self.label.setText(_translate("cov_subgroup_dialog", "Covariate for \n"
"subgroups:"))
