# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ali-Salman\Documents\Biostatistics\openmeta-analyst-community\src\forms\diagnostic_metrics.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_diag_metric(object):
    def setupUi(self, diag_metric):
        diag_metric.setObjectName("diag_metric")
        diag_metric.setWindowModality(QtCore.Qt.ApplicationModal)
        diag_metric.resize(348, 160)
        diag_metric.setMinimumSize(QtCore.QSize(250, 140))
        diag_metric.setMaximumSize(QtCore.QSize(10000, 10000))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        diag_metric.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/misc/meta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        diag_metric.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(diag_metric)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.metrics_grp_box = QtWidgets.QGroupBox(diag_metric)
        self.metrics_grp_box.setObjectName("metrics_grp_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.metrics_grp_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.chk_box_sens = QtWidgets.QCheckBox(self.metrics_grp_box)
        self.chk_box_sens.setChecked(True)
        self.chk_box_sens.setObjectName("chk_box_sens")
        self.gridLayout.addWidget(self.chk_box_sens, 0, 0, 1, 1)
        self.chk_box_spec = QtWidgets.QCheckBox(self.metrics_grp_box)
        self.chk_box_spec.setChecked(True)
        self.chk_box_spec.setObjectName("chk_box_spec")
        self.gridLayout.addWidget(self.chk_box_spec, 0, 1, 1, 1)
        self.chk_box_lr = QtWidgets.QCheckBox(self.metrics_grp_box)
        self.chk_box_lr.setChecked(True)
        self.chk_box_lr.setObjectName("chk_box_lr")
        self.gridLayout.addWidget(self.chk_box_lr, 2, 0, 1, 1)
        self.chk_box_dor = QtWidgets.QCheckBox(self.metrics_grp_box)
        self.chk_box_dor.setChecked(True)
        self.chk_box_dor.setObjectName("chk_box_dor")
        self.gridLayout.addWidget(self.chk_box_dor, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2.addWidget(self.metrics_grp_box, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(
            200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_ok = QtWidgets.QPushButton(diag_metric)
        self.btn_ok.setMaximumSize(QtCore.QSize(75, 23))
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout.addWidget(self.btn_ok)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(diag_metric)
        QtCore.QMetaObject.connectSlotsByName(diag_metric)

    def retranslateUi(self, diag_metric):
        _translate = QtCore.QCoreApplication.translate
        diag_metric.setWindowTitle(_translate("diag_metric", "Diagnostic Metrics"))
        self.metrics_grp_box.setTitle(
            _translate("diag_metric", "Select Metrics for Analysis")
        )
        self.chk_box_sens.setText(_translate("diag_metric", "Sensitivity"))
        self.chk_box_spec.setText(_translate("diag_metric", "Specificity"))
        self.chk_box_lr.setText(_translate("diag_metric", "Likelihood Ratio"))
        self.chk_box_dor.setText(_translate("diag_metric", "Diagnostic Odds Ratio"))
        self.btn_ok.setText(_translate("diag_metric", "Next >"))


import icons_rc
