# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ali-Salman\Documents\Biostatistics\openmeta-analyst-community\src\forms\diag_explain_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_diag_explain_window(object):
    def setupUi(self, diag_explain_window):
        diag_explain_window.setObjectName("diag_explain_window")
        diag_explain_window.resize(510, 239)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/misc/meta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        diag_explain_window.setWindowIcon(icon)
        diag_explain_window.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(diag_explain_window)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(diag_explain_window)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.dont_show_again_chk_box = QtWidgets.QCheckBox(diag_explain_window)
        self.dont_show_again_chk_box.setObjectName("dont_show_again_chk_box")
        self.verticalLayout.addWidget(self.dont_show_again_chk_box)
        self.buttonBox = QtWidgets.QDialogButtonBox(diag_explain_window)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(diag_explain_window)
        self.buttonBox.accepted.connect(diag_explain_window.accept) # type: ignore
        self.buttonBox.rejected.connect(diag_explain_window.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(diag_explain_window)

    def retranslateUi(self, diag_explain_window):
        _translate = QtCore.QCoreApplication.translate
        diag_explain_window.setWindowTitle(_translate("diag_explain_window", "Diagnostic MA with Multiple Metrics"))
        self.textBrowser.setHtml(_translate("diag_explain_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">A note on diagnostic meta-analysis for multiple metrics</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:14pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">It looks like you\'re conducting meta-analyses for multiple diagnostic metrics. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Due to statistical properties of these metrics, different methods are available for sensitivity and specificity than are for likelihood and diagnostic odds ratios. So now we\'re going to first ask you to pick a meta-analysis method (and parameters) to use for sensitivity/specificity, and then we\'re going to ask you to pick a method to use for likelihood and diagnostic odds ratios. </span></p></body></html>"))
        self.dont_show_again_chk_box.setText(_translate("diag_explain_window", "don\'t show this message next time"))
import icons_rc
