# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ali-Salman\Documents\Biostatistics\openmeta-analyst-community\src\forms\diagnostic_data_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DiagnosticDataForm(object):
    def setupUi(self, DiagnosticDataForm):
        DiagnosticDataForm.setObjectName("DiagnosticDataForm")
        DiagnosticDataForm.resize(380, 412)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/misc/meta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        DiagnosticDataForm.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(DiagnosticDataForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.two_by_two_table = QtWidgets.QTableWidget(DiagnosticDataForm)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.two_by_two_table.sizePolicy().hasHeightForWidth()
        )
        self.two_by_two_table.setSizePolicy(sizePolicy)
        self.two_by_two_table.setMinimumSize(QtCore.QSize(0, 0))
        self.two_by_two_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.two_by_two_table.setFont(font)
        self.two_by_two_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.two_by_two_table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.two_by_two_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.two_by_two_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.two_by_two_table.setAlternatingRowColors(True)
        self.two_by_two_table.setGridStyle(QtCore.Qt.DashLine)
        self.two_by_two_table.setRowCount(3)
        self.two_by_two_table.setColumnCount(3)
        self.two_by_two_table.setObjectName("two_by_two_table")
        item = QtWidgets.QTableWidgetItem()
        self.two_by_two_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.two_by_two_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.two_by_two_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.two_by_two_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.two_by_two_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.two_by_two_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.two_by_two_table)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.clear_Btn = QtWidgets.QPushButton(DiagnosticDataForm)
        self.clear_Btn.setObjectName("clear_Btn")
        self.horizontalLayout_6.addWidget(self.clear_Btn)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_6.addItem(spacerItem1)
        self.back_calc_Btn = QtWidgets.QPushButton(DiagnosticDataForm)
        self.back_calc_Btn.setEnabled(False)
        self.back_calc_Btn.setObjectName("back_calc_Btn")
        self.horizontalLayout_6.addWidget(self.back_calc_Btn)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.prevalence_lbl = QtWidgets.QLabel(DiagnosticDataForm)
        self.prevalence_lbl.setObjectName("prevalence_lbl")
        self.horizontalLayout_3.addWidget(self.prevalence_lbl)
        self.prevalence_txt_box = QtWidgets.QLineEdit(DiagnosticDataForm)
        self.prevalence_txt_box.setMinimumSize(QtCore.QSize(75, 0))
        self.prevalence_txt_box.setMaximumSize(QtCore.QSize(75, 16777215))
        self.prevalence_txt_box.setObjectName("prevalence_txt_box")
        self.horizontalLayout_3.addWidget(self.prevalence_txt_box)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_13 = QtWidgets.QLabel(DiagnosticDataForm)
        self.label_13.setMinimumSize(QtCore.QSize(50, 0))
        self.label_13.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.effect_cbo_box = QtWidgets.QComboBox(DiagnosticDataForm)
        self.effect_cbo_box.setMinimumSize(QtCore.QSize(100, 20))
        self.effect_cbo_box.setMaximumSize(QtCore.QSize(76, 20))
        self.effect_cbo_box.setObjectName("effect_cbo_box")
        self.horizontalLayout_2.addWidget(self.effect_cbo_box)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(DiagnosticDataForm)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem4 = QtWidgets.QSpacerItem(
            26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout.addItem(spacerItem4, 0, 0, 2, 1)
        self.ci_label = QtWidgets.QLabel(self.groupBox)
        self.ci_label.setObjectName("ci_label")
        self.gridLayout.addWidget(self.ci_label, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(
            26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout.addItem(spacerItem5, 0, 3, 2, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setMinimumSize(QtCore.QSize(0, 20))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_14.setFont(font)
        self.label_14.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft
        )
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.effect_txt_box = QtWidgets.QLineEdit(self.groupBox)
        self.effect_txt_box.setMinimumSize(QtCore.QSize(50, 20))
        self.effect_txt_box.setMaximumSize(QtCore.QSize(50, 20))
        self.effect_txt_box.setObjectName("effect_txt_box")
        self.horizontalLayout_7.addWidget(self.effect_txt_box)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.low_txt_box = QtWidgets.QLineEdit(self.groupBox)
        self.low_txt_box.setMinimumSize(QtCore.QSize(50, 20))
        self.low_txt_box.setMaximumSize(QtCore.QSize(50, 20))
        self.low_txt_box.setObjectName("low_txt_box")
        self.horizontalLayout_5.addWidget(self.low_txt_box)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.high_txt_box = QtWidgets.QLineEdit(self.groupBox)
        self.high_txt_box.setMinimumSize(QtCore.QSize(50, 20))
        self.high_txt_box.setMaximumSize(QtCore.QSize(50, 20))
        self.high_txt_box.setObjectName("high_txt_box")
        self.horizontalLayout_5.addWidget(self.high_txt_box)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 2, 1, 1)
        self.ci_label.raise_()
        self.verticalLayout.addWidget(self.groupBox)
        self.line = QtWidgets.QFrame(DiagnosticDataForm)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.inconsistencyLabel = QtWidgets.QLabel(DiagnosticDataForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.inconsistencyLabel.setFont(font)
        self.inconsistencyLabel.setObjectName("inconsistencyLabel")
        self.horizontalLayout_4.addWidget(self.inconsistencyLabel)
        spacerItem6 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem6)
        self.buttonBox = QtWidgets.QDialogButtonBox(DiagnosticDataForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.prevalence_lbl.setBuddy(self.prevalence_txt_box)

        self.retranslateUi(DiagnosticDataForm)
        self.buttonBox.accepted.connect(DiagnosticDataForm.accept)  # type: ignore
        self.buttonBox.rejected.connect(DiagnosticDataForm.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DiagnosticDataForm)
        DiagnosticDataForm.setTabOrder(self.two_by_two_table, self.clear_Btn)
        DiagnosticDataForm.setTabOrder(self.clear_Btn, self.back_calc_Btn)
        DiagnosticDataForm.setTabOrder(self.back_calc_Btn, self.prevalence_txt_box)
        DiagnosticDataForm.setTabOrder(self.prevalence_txt_box, self.effect_cbo_box)
        DiagnosticDataForm.setTabOrder(self.effect_cbo_box, self.buttonBox)

    def retranslateUi(self, DiagnosticDataForm):
        _translate = QtCore.QCoreApplication.translate
        DiagnosticDataForm.setWindowTitle(
            _translate("DiagnosticDataForm", "Diagnostic Data")
        )
        item = self.two_by_two_table.verticalHeaderItem(0)
        item.setText(_translate("DiagnosticDataForm", "(Test) +"))
        item = self.two_by_two_table.verticalHeaderItem(1)
        item.setText(_translate("DiagnosticDataForm", "(Test) -"))
        item = self.two_by_two_table.verticalHeaderItem(2)
        item.setText(_translate("DiagnosticDataForm", "Total"))
        item = self.two_by_two_table.horizontalHeaderItem(0)
        item.setText(_translate("DiagnosticDataForm", "(Disease) +"))
        item = self.two_by_two_table.horizontalHeaderItem(1)
        item.setText(_translate("DiagnosticDataForm", "(Disease) -"))
        item = self.two_by_two_table.horizontalHeaderItem(2)
        item.setText(_translate("DiagnosticDataForm", "Total"))
        self.clear_Btn.setText(_translate("DiagnosticDataForm", "Clear Form"))
        self.back_calc_Btn.setText(
            _translate("DiagnosticDataForm", "Back-Calculate Table")
        )
        self.prevalence_lbl.setText(_translate("DiagnosticDataForm", "Prevalence"))
        self.label_13.setText(_translate("DiagnosticDataForm", "Metric"))
        self.ci_label.setToolTip(
            _translate(
                "DiagnosticDataForm",
                "Use the box to the left to set the % confidence interval",
            )
        )
        self.ci_label.setText(
            _translate("DiagnosticDataForm", "X% Confidence Interval")
        )
        self.label_14.setText(_translate("DiagnosticDataForm", "Est."))
        self.label.setText(_translate("DiagnosticDataForm", "["))
        self.label_4.setText(_translate("DiagnosticDataForm", ","))
        self.label_3.setText(_translate("DiagnosticDataForm", "]"))
        self.inconsistencyLabel.setText(
            _translate("DiagnosticDataForm", "INCONSISTENT FORM")
        )


import icons_rc
