# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ali-Salman\Documents\Biostatistics\openmeta-analyst-community\src\forms\cov_reg_dlg2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cov_reg_dialog(object):
    def setupUi(self, cov_reg_dialog):
        cov_reg_dialog.setObjectName("cov_reg_dialog")
        cov_reg_dialog.resize(401, 323)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        cov_reg_dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/misc/meta.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        cov_reg_dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(cov_reg_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(cov_reg_dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.cov_grp_box = QtWidgets.QGroupBox(cov_reg_dialog)
        self.cov_grp_box.setObjectName("cov_grp_box")
        self.verticalLayout.addWidget(self.cov_grp_box)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.diagnostic_group_box = QtWidgets.QGroupBox(cov_reg_dialog)
        self.diagnostic_group_box.setObjectName("diagnostic_group_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.diagnostic_group_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dor_radio = QtWidgets.QRadioButton(self.diagnostic_group_box)
        self.dor_radio.setChecked(True)
        self.dor_radio.setObjectName("dor_radio")
        self.verticalLayout_3.addWidget(self.dor_radio)
        self.sensitivity_radio = QtWidgets.QRadioButton(self.diagnostic_group_box)
        self.sensitivity_radio.setChecked(False)
        self.sensitivity_radio.setObjectName("sensitivity_radio")
        self.verticalLayout_3.addWidget(self.sensitivity_radio)
        self.fixed_radio = QtWidgets.QRadioButton(self.diagnostic_group_box)
        self.fixed_radio.setObjectName("fixed_radio")
        self.verticalLayout_3.addWidget(self.fixed_radio)
        self.verticalLayout.addWidget(self.diagnostic_group_box)
        self.groupBox = QtWidgets.QGroupBox(cov_reg_dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.random_effects_radio = QtWidgets.QRadioButton(self.groupBox)
        self.random_effects_radio.setChecked(True)
        self.random_effects_radio.setObjectName("random_effects_radio")
        self.verticalLayout_2.addWidget(self.random_effects_radio)
        self.fixed_effects_radio = QtWidgets.QRadioButton(self.groupBox)
        self.fixed_effects_radio.setObjectName("fixed_effects_radio")
        self.verticalLayout_2.addWidget(self.fixed_effects_radio)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(cov_reg_dialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(cov_reg_dialog)
        QtCore.QMetaObject.connectSlotsByName(cov_reg_dialog)

    def retranslateUi(self, cov_reg_dialog):
        _translate = QtCore.QCoreApplication.translate
        cov_reg_dialog.setWindowTitle(_translate("cov_reg_dialog", "select covariates"))
        self.label.setText(_translate("cov_reg_dialog", "select covariates for regression:"))
        self.cov_grp_box.setTitle(_translate("cov_reg_dialog", "available covariates"))
        self.diagnostic_group_box.setTitle(_translate("cov_reg_dialog", "metric"))
        self.dor_radio.setText(_translate("cov_reg_dialog", "diagnostic odds ratio"))
        self.sensitivity_radio.setText(_translate("cov_reg_dialog", "sensitivity"))
        self.fixed_radio.setText(_translate("cov_reg_dialog", "specificity"))
        self.groupBox.setTitle(_translate("cov_reg_dialog", "model type"))
        self.random_effects_radio.setText(_translate("cov_reg_dialog", "random effects"))
        self.fixed_effects_radio.setText(_translate("cov_reg_dialog", "fixed effects"))
import icons_rc
