# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ali-Salman\Documents\Biostatistics\openmeta-analyst-community\src\forms\running.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_running(object):
    def setupUi(self, running):
        running.setObjectName("running")
        running.setWindowModality(QtCore.Qt.ApplicationModal)
        running.resize(373, 70)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        running.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/misc/meta.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        running.setWindowIcon(icon)
        running.setSizeGripEnabled(False)
        running.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(running)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progress_bar = QtWidgets.QProgressBar(running)
        self.progress_bar.setMaximum(0)
        self.progress_bar.setProperty("value", -1)
        self.progress_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout.addWidget(self.progress_bar)

        self.retranslateUi(running)
        QtCore.QMetaObject.connectSlotsByName(running)

    def retranslateUi(self, running):
        _translate = QtCore.QCoreApplication.translate
        running.setWindowTitle(_translate("running", "running analysis..."))
import icons_rc
