# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ali-Salman\Documents\Biostatistics\openmeta-analyst-community\src\forms\welcome_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(350, 230)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WizardPage.sizePolicy().hasHeightForWidth())
        WizardPage.setSizePolicy(sizePolicy)
        WizardPage.setMinimumSize(QtCore.QSize(350, 230))
        WizardPage.setMaximumSize(QtCore.QSize(350, 230))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WizardPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.create_new_btn = QtWidgets.QPushButton(WizardPage)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/function_icon_set/function_icon_set/add_48.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.create_new_btn.setIcon(icon)
        self.create_new_btn.setObjectName("create_new_btn")
        self.verticalLayout.addWidget(self.create_new_btn)
        self.import_csv_btn = QtWidgets.QPushButton(WizardPage)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/function_icon_set/function_icon_set/box_download_48.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.import_csv_btn.setIcon(icon1)
        self.import_csv_btn.setObjectName("import_csv_btn")
        self.verticalLayout.addWidget(self.import_csv_btn)
        self.open_recent_btn = QtWidgets.QPushButton(WizardPage)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/function_icon_set/function_icon_set/folder_48.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.open_recent_btn.setIcon(icon2)
        self.open_recent_btn.setObjectName("open_recent_btn")
        self.verticalLayout.addWidget(self.open_recent_btn)
        self.open_btn = QtWidgets.QPushButton(WizardPage)
        self.open_btn.setIcon(icon2)
        self.open_btn.setObjectName("open_btn")
        self.verticalLayout.addWidget(self.open_btn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_2.addItem(spacerItem2)
        self.line = QtWidgets.QFrame(WizardPage)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.oma_onlineLabel = QtWidgets.QLabel(WizardPage)
        self.oma_onlineLabel.setMinimumSize(QtCore.QSize(120, 0))
        self.oma_onlineLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.oma_onlineLabel.setOpenExternalLinks(True)
        self.oma_onlineLabel.setObjectName("oma_onlineLabel")
        self.horizontalLayout_2.addWidget(self.oma_onlineLabel)
        self.line_3 = QtWidgets.QFrame(WizardPage)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.how_to_citeLabel = QtWidgets.QLabel(WizardPage)
        self.how_to_citeLabel.setEnabled(False)
        self.how_to_citeLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.how_to_citeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.how_to_citeLabel.setOpenExternalLinks(True)
        self.how_to_citeLabel.setObjectName("how_to_citeLabel")
        self.horizontalLayout_2.addWidget(self.how_to_citeLabel)
        self.line_4 = QtWidgets.QFrame(WizardPage)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        self.helpLabel = QtWidgets.QLabel(WizardPage)
        self.helpLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.helpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.helpLabel.setOpenExternalLinks(True)
        self.helpLabel.setObjectName("helpLabel")
        self.horizontalLayout_2.addWidget(self.helpLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage"))
        WizardPage.setTitle(_translate("WizardPage", "What would you like to do?"))
        self.create_new_btn.setText(_translate("WizardPage", "Create a new dataset"))
        self.import_csv_btn.setText(_translate("WizardPage", "Import CSV"))
        self.open_recent_btn.setText(_translate("WizardPage", "Open recent..."))
        self.open_btn.setText(_translate("WizardPage", "Open an existing dataset"))
        self.oma_onlineLabel.setText(
            _translate(
                "WizardPage",
                '<html><head/><body><p><a href="http://www.cebm.brown.edu/open_meta"><span style=" text-decoration: underline; color:#0000ff;">OpenMeta Website</span></a></p></body></html>',
            )
        )
        self.how_to_citeLabel.setText(
            _translate(
                "WizardPage",
                '<a href="https://www.jstatsoft.org/article/view/v049i05">How to cite</a>',
            )
        )
        self.helpLabel.setText(
            _translate(
                "WizardPage",
                '<a href="http://tuftscaes.org/open_meta/help/openMA_help.html">Help</a>',
            )
        )


import icons_rc
